eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 12580
spring:
  application:
    name: resource-server
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,\
      classpath:/static/,classpath:/public/,file:${web.upload-path}
web:
  upload-path: D:/imgs/