eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9999
spring:
  application:
    name: gateway-zuul
zuul:
  retryable: false
  host:
    connect-timeout-millis: 35000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000